POST http://localhost:8080/api/users/register HTTP/1.1
content-type: application/json

{
  "firstName": "Wary",
  "lastName": "Sawyer",
  "email": "wary.sawyer@email.com",
  "password": "password"
}

###

POST http://localhost:8080/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "mary.sawyer@email.com",
  "password": "password"
}

###
GET http://localhost:8080/api/categories HTTP/1.1