POST http://localhost:8080/api/users/register HTTP/1.1
content-type: application/json

{
  "firstName": "Uary",
  "lastName": "Sawyer",
  "email": "uary.sawyer@email.com",
  "password": "password"
}

###

POST http://localhost:8080/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "mary.sawyer@email.com",
  "password": "password"
}

###
GET http://localhost:8080/api/categories HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg1MjA4ODgsImV4cCI6MTY0ODUyODA4OCwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.NxPjlIiDiro1fZ96l1ixLg1LJll_QAthIIQ02GeRzGo

###
POST http://localhost:8080/api/categories HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg1MjA4ODgsImV4cCI6MTY0ODUyODA4OCwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.NxPjlIiDiro1fZ96l1ixLg1LJll_QAthIIQ02GeRzGo

{
  "title": "title_4",
  "description": "description_4"
}

###

GET http://localhost:8080/api/categories/7 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg1Mjg4ODQsImV4cCI6MTY0ODUzNjA4NCwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.67v4PS4ZGiaoCzzIlKoR4DTGeCoSEhSXdnZr775zXq0

###

GET http://localhost:8080/api/categories/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg1Mjg4ODQsImV4cCI6MTY0ODUzNjA4NCwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.67v4PS4ZGiaoCzzIlKoR4DTGeCoSEhSXdnZr775zXq0

###
PUT http://localhost:8080/api/categories/7 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg1Mjg4ODQsImV4cCI6MTY0ODUzNjA4NCwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.67v4PS4ZGiaoCzzIlKoR4DTGeCoSEhSXdnZr775zXq0

{
  "title": "Shopping",
  "description": "Shopping expenses"
}

###
POST http://localhost:8080/api/categories/8/transactions HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg3MDEzNDEsImV4cCI6MTY0ODcwODU0MSwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.K5QMi73pxsbzUIRsfSOzvXtCWVPPpgpTCYTgjk6KUlo

{
  "amount": 5000,
  "note": "Easter shopping",
  "transactionDate": 1577817000000
}

###
GET http://localhost:8080/api/categories/8/transactions/1003 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg3MDEzNDEsImV4cCI6MTY0ODcwODU0MSwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.K5QMi73pxsbzUIRsfSOzvXtCWVPPpgpTCYTgjk6KUlo

###
GET http://localhost:8080/api/categories/8/transactions HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg3MDEzNDEsImV4cCI6MTY0ODcwODU0MSwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.K5QMi73pxsbzUIRsfSOzvXtCWVPPpgpTCYTgjk6KUlo

###
PUT http://localhost:8080/api/categories/8/transactions/1003 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDg3MDEzNDEsImV4cCI6MTY0ODcwODU0MSwidXNlcklkIjoxMSwiZW1haWwiOiJtYXJ5LnNhd3llckBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJNYXJ5IiwibGFzdE5hbWUiOiJTYXd5ZXIifQ.K5QMi73pxsbzUIRsfSOzvXtCWVPPpgpTCYTgjk6KUlo

{
   "amount": 4000.0,
  "transactionDate": 1577817000000,
  "note": "Mer shopping"
}